### ISSUE TITLE
macos build issue: "no valid value for variant 'cuda'"

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1001]
I tried installing Ascent via uberenv on a new Mac laptop, but it fails with this error:

```
benwibking@Bens-MacBook-Pro ascent % python3 scripts/uberenv/uberenv.py --install --prefix="build"

[uberenv python: /opt/homebrew/opt/python@3.10/bin/python3.10]
[uberenv project settings:
  package_name: ascent
  package_version: develop
  package_source_dir: ../../
  spack_build_mode: uberenv-pkg
  spack_configs_path: scripts/uberenv_configs/spack_configs/configs
  spack_packages_path: scripts/uberenv_configs/packages
  spack_url: https://github.com/spack/spack
  spack_branch: develop
  spack_activate: {'py-numpy': ['+python'], 'py-mpi4py': ['+python', '+mpi'], 'conduit': ['+python'], 'py-sphinx': ['+python', '+doc'], 'py-sphinx-rtd-theme': ['+python', '+doc']}
  force_commandline_prefix: False
]
[uberenv command line options:
  install: True
  prefix: build
  spec: None
  vcpkg_triplet: None
  mirror: None
  create_mirror: False
  upstream: None
  reuse: False
  spack_config_dir: None
  vcpkg_ports_path: None
  package_name: None
  spack_build_mode: None
  package_final_phase: None
  package_source_dir: None
  project_json: /Users/benwibking/ascent/.uberenv_config.json
  build_jobs: None
  ignore_ssl_errors: False
  repo_pull: False
  spack_clean: False
  run_tests: False
  macos_sdk_env_setup: False
  setup_only: False
]
[uberenv spack build mode: install]
[skipping MACOSX env var setup]
[spack spec: @develop%apple-clang]
[info: destination '/Users/benwibking/ascent/build' already exists]
[installing to: /Users/benwibking/ascent/build]
[info: destination '/Users/benwibking/ascent/build/spack' already exists]
[spack python: /opt/homebrew/opt/python@3.10/bin/python3.10]
[disabling config scope (except defaults) in: /Users/benwibking/ascent/build/spack/lib/spack/spack/config.py]
[copying uberenv compiler and packages settings from /Users/benwibking/ascent/scripts/uberenv_configs/spack_configs/configs/darwin]
[exe: cp /Users/benwibking/ascent/scripts/uberenv_configs/spack_configs/configs/darwin/compilers.yaml /Users/benwibking/ascent/build/spack/etc/spack/defaults/]
[copying patched packages from /Users/benwibking/ascent/scripts/uberenv_configs/packages/*]
[exe: spack/bin/spack clean --misc-cache --failures --python-cache]
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
[exe: spack/bin/spack spec --install-status --very-long ascent@develop%apple-clang]
==> Error: No valid value for variant 'cuda' of package 'ascent'

[exe: spack/bin/spack install ascent@develop%apple-clang]
==> Error: No valid value for variant 'cuda' of package 'ascent'
[ERROR: failure of spack install/dev-build]
```

**Comment by cyrush** [comment]
@BenWibking  Possible cause is that uberenv is tracking spack develop right now. I need to pin it back down to provide stability.

That said, I am puzzled that cuda is getting into the mix at all. 

Question + Suggestion:

Was this a fresh checkout, does the uberenv `--pull`  option help?

If that does not help, can you try modifying:

https://github.com/LLNL/uberenv/blob/4971b8c7591cac0b9f18a60264ca9215cffa1fd0/uberenv.py#L836

To be:

```
spec_cmd = "spack/bin/spack --debug --stacktrace spec {0} {1}{2}".format(options,self.pkg_name,self.opts["spec"])
```

To see if that gives us more context?

**Comment by BenWibking** [comment]
Yes, it was a fresh checkout, and adding `--pull` doesn't help.

Here's the verbose output:

```
➜  ascent git:(develop) ✗ python3 scripts/uberenv/uberenv.py --install --prefix="build" --pull
[uberenv python: /Library/Developer/CommandLineTools/usr/bin/python3]
[uberenv project settings:
  package_name: ascent
  package_version: develop
  package_source_dir: ../../
  spack_build_mode: uberenv-pkg
  spack_configs_path: scripts/uberenv_configs/spack_configs/configs
  spack_packages_path: scripts/uberenv_configs/packages
  spack_url: https://github.com/spack/spack
  spack_branch: develop
  spack_activate: {'py-numpy': ['+python'], 'py-mpi4py': ['+python', '+mpi'], 'conduit': ['+python'], 'py-sphinx': ['+python', '+doc'], 'py-sphinx-rtd-theme': ['+python', '+doc']}
  force_commandline_prefix: False
]
[uberenv command line options:
  install: True
  prefix: build
  spec: None
  vcpkg_triplet: None
  mirror: None
  create_mirror: False
  upstream: None
  reuse: False
  spack_config_dir: None
  vcpkg_ports_path: None
  package_name: None
  spack_build_mode: None
  package_final_phase: None
  package_source_dir: None
  project_json: /Users/benwibking/ascent/.uberenv_config.json
  build_jobs: None
  ignore_ssl_errors: False
  repo_pull: True
  spack_clean: False
  run_tests: False
  macos_sdk_env_setup: False
  setup_only: False
]
[uberenv spack build mode: install]
[skipping MACOSX env var setup]
[spack spec: @develop%apple-clang]
[info: destination '/Users/benwibking/ascent/build' already exists]
[installing to: /Users/benwibking/ascent/build]
[info: destination '/Users/benwibking/ascent/build/spack' already exists]
[exe: git stash]
Saved working directory and index state WIP on develop: 08261af4 py-breathe: add new version and improve version constraints (#31857)
[exe: git pull]
Already up to date.
[spack python: /Library/Developer/CommandLineTools/usr/bin/python3]
[disabling config scope (except defaults) in: /Users/benwibking/ascent/build/spack/lib/spack/spack/config.py]
[copying uberenv compiler and packages settings from /Users/benwibking/ascent/scripts/uberenv_configs/spack_configs/configs/darwin]
[exe: cp /Users/benwibking/ascent/scripts/uberenv_configs/spack_configs/configs/darwin/compilers.yaml /Users/benwibking/ascent/build/spack/etc/spack/defaults/]
[copying patched packages from /Users/benwibking/ascent/scripts/uberenv_configs/packages/*]
[exe: spack/bin/spack clean --misc-cache --failures --python-cache]
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
[exe: spack/bin/spack --debug --stacktrace spec --install-status --very-long ascent@develop%apple-clang]
/Users/benwibking/ascent/build/spack/lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-31-14:24:07.708470] Imported spec from built-in commands
/Users/benwibking/ascent/build/spack/lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-31-14:24:07.708982] Imported spec from built-in commands
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.712023] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.720884] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.720967] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.721043] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.721773] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.724624] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.724720] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.724795] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.724905] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.724985] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.725063] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.725139] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/database.py:389 ==> [2022-08-31-14:24:07.726127] DATABASE LOCK TIMEOUT: 3s
/Users/benwibking/ascent/build/spack/lib/spack/spack/database.py:395 ==> [2022-08-31-14:24:07.726195] PACKAGE LOCK TIMEOUT: No timeout
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.740239] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.740432] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.740536] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.740635] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/upstreams.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.741100] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.750012] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.750121] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.750218] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/database.py:389 ==> [2022-08-31-14:24:07.750321] DATABASE LOCK TIMEOUT: 3s
/Users/benwibking/ascent/build/spack/lib/spack/spack/database.py:395 ==> [2022-08-31-14:24:07.750398] PACKAGE LOCK TIMEOUT: No timeout
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:626 ==> [2022-08-31-14:24:07.750499] [BOOTSTRAP CONFIG SCOPE] name=_builtin
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.750737] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.753514] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.753613] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.753722] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:637 ==> [2022-08-31-14:24:07.753824] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/benwibking/ascent/build/spack/etc/spack/defaults
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:638 ==> [2022-08-31-14:24:07.753893] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:637 ==> [2022-08-31-14:24:07.753963] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/benwibking/.spack/bootstrap/config
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:638 ==> [2022-08-31-14:24:07.754030] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/benwibking/.spack/bootstrap/config/darwin
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.755048] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.762711] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.762826] Skipping nonexistent config path /Users/benwibking/.spack/bootstrap/config/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.762944] Reading config from file /Users/benwibking/.spack/bootstrap/config/darwin/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:763 ==> [2022-08-31-14:24:07.781673] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=aarch64
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:522 ==> [2022-08-31-14:24:07.781829] [BOOTSTRAP MODULE clingo] Try importing from Python
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.782133] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.785282] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.785373] Skipping nonexistent config path /Users/benwibking/.spack/bootstrap/config/bootstrap.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:07.890528] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.899327] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:07.899458] Skipping nonexistent config path /Users/benwibking/.spack/bootstrap/config/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/util/executable.py:197 ==> [2022-08-31-14:24:18.437908] '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8' '-c' '
import json
from sysconfig import (
    get_config_vars,
    get_config_h_filename,
    get_makefile_filename,
    get_paths,
)

config = get_config_vars()
config['"'"'config_h_filename'"'"'] = get_config_h_filename()
config['"'"'makefile_filename'"'"'] = get_makefile_filename()
config.update(get_paths())

print(json.dumps(config))
'
/Users/benwibking/ascent/build/spack/lib/spack/spack/bootstrap.py:107 ==> [2022-08-31-14:24:18.470919] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=aarch64 ^python@3.8 /o4gdbtk74nevc5z6u6m3padxcxu3pbla" provides the "clingo" Python module
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.472022] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/concretizer.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.474901] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/concretizer.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.474984] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/concretizer.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.475058] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/concretizer.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.475207] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/repos.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.476062] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/repos.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.476148] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/repos.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.476229] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/repos.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.485855] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.494626] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.494726] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.494815] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/config.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.496203] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/mirrors.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.496817] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/mirrors.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.496904] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/mirrors.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.496985] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/mirrors.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/util/web.py:399 ==> [2022-08-31-14:24:18.498508] Checking existence of https://mirror.spack.io/build_cache/index.json
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.787242] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.795018] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.795113] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.795198] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/compilers.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.795410] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/packages.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1010 ==> [2022-08-31-14:24:18.809264] Reading config from file /Users/benwibking/ascent/build/spack/etc/spack/defaults/darwin/packages.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.813314] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/packages.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/config.py:1000 ==> [2022-08-31-14:24:18.813400] Skipping nonexistent config path /Users/benwibking/ascent/build/spack/etc/spack/darwin/packages.yaml
/Users/benwibking/ascent/build/spack/lib/spack/spack/main.py:964 ==> [2022-08-31-14:24:27.154049] SpackError: No valid value for variant 'cuda' of package 'ascent'
/Users/benwibking/ascent/build/spack/lib/spack/spack/error.py:54 ==> [2022-08-31-14:24:27.158728] Error: No valid value for variant 'cuda' of package 'ascent'
Traceback (most recent call last):
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/spec.py", line 2924, in concretize
    self._new_concretize(tests)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/spec.py", line 2899, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/solver/asp.py", line 2380, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/solver/asp.py", line 706, in solve
    answers = builder.build_specs(tuples)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/solver/asp.py", line 2232, in build_specs
    action(*args)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/solver/asp.py", line 2066, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: No valid value for variant 'cuda' of package 'ascent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/Users/benwibking/ascent/build/spack/lib/spack/spack/cmd/__init__.py", line 241, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: No valid value for variant 'cuda' of package 'ascent'

[exe: spack/bin/spack install ascent@develop%apple-clang]
==> Error: No valid value for variant 'cuda' of package 'ascent'
[ERROR: failure of spack install/dev-build]
```

**Comment by cyrush** [comment]
@BenWibking one more q: What macOS is your new laptop running?

We might be missing an entry in our darwin compilers setup.

I would expect a better error message from spack about the compilers, but the solver is a complex entity.

**Comment by BenWibking** [comment]
I'm running macOS Monterey 12.5.1. It's an M1-based Mac, so that could make a difference. I hope it still works on ARM, though!

**Comment by cyrush** [comment]
Thanks, I added an entry for monterey + arm in the `task/2022_08_macos_monterey` branch.

(https://github.com/Alpine-DAV/ascent/tree/task/2022_08_macos_monterey)

Can you see if this helps. The spack configuration files are in a git submodule, so make sure to do a:

```
git fetch
git checkout task/2022_08_macos_monterey
git submodule update
```

Before testing.

If that solves, I can merge these in via PR #1004.

**Comment by BenWibking** [comment]
It's building now. I had to change the gfortran path to `/opt/homebrew/bin/gfortran` to get it to work. I think this is because new installations of Homebrew install to `/opt/homebrew` whereas older installations still use `/usr/local`.

**Comment by BenWibking** [comment]
It's now failing at the raja and conduit builds:

```
==> Installing raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt
==> No binary for raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt found: installing from source
==> Using cached archive: /Users/benwibking/ascent/build/spack/var/spack/cache/_source-cache/git//LLNL/RAJA.git/v2022.03.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwfc/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_FIND_FRAMEWORK:STRING=LAST' '-DCMAKE_FIND_APPBUNDLE:STRING=LAST' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt/lib;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt/lib64;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/camp-2022.03.0-vyv6sqdl2ogviz73h4zj3xwv5ahnrdti/lib;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/ncurses-6.3-euuhharcgo4xhz7czjhk7ouhacrvxz4h/lib;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openssl-1.1.1q-4cvfs2hejtltukqsytzzbnsadxoaldle/lib;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/zlib-1.2.12-ke4alug7ypoxp37jb6namwlxssmws4kp/lib' '-DCMAKE_PREFIX_PATH:STRING=/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/camp-2022.03.0-vyv6sqdl2ogviz73h4zj3xwv5ahnrdti;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/blt-0.5.1-k27wnxen7s4agztjiiplquomayrwxjqw;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwfc;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openssl-1.1.1q-4cvfs2hejtltukqsytzzbnsadxoaldle;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/zlib-1.2.12-ke4alug7ypoxp37jb6namwlxssmws4kp;/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/ncurses-6.3-euuhharcgo4xhz7czjhk7ouhacrvxz4h' '-C' '/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt/spack-src/Bens-MacBook-Pro.local-darwin-monterey-m1-apple-clang@13.1.6.cmake' '/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt/spack-src'

1 error found in build log:
     35    -- Found Git: /usr/bin/git (found version "2.32.1 (Apple Git-133)")
     36    -- Git Support is ON
     37    -- Git Executable: /usr/bin/git
     38    -- Git Version: 2.32.1 (Apple Git-133)
     39    -- MPI Support is OFF
     40    -- OpenMP Support is ON
  >> 41    CMake Error at /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd
           2xmshjnlg2phwfc/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     42      Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
     43    Call Stack (most recent call first):
     44      /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phw
           fc/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     45      /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phw
           fc/share/cmake-3.23/Modules/FindOpenMP.cmake:545 (find_package_handle_standard_args)
     46      /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/blt-0.5.1-k27wnxen7s4agztjiiplquomayrwxjqw/
           cmake/thirdparty/SetupOpenMP.cmake:11 (find_package)
     47      /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/blt-0.5.1-k27wnxen7s4agztjiiplquomayrwxjqw/
           cmake/thirdparty/SetupThirdParty.cmake:38 (include)

See build log for details:
  /var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt/spack-build-out.txt

==> Warning: Skipping build of ascent-develop-ammwyafmmzpvs2ykqjyyqbni324mrd4s since raja-2022.03.0-q54wfqcqok7svkhvjmm7qg4mi3vzo5tt failed
[+] /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/parmetis-4.0.3-v4vmqzurzexqnbc3ief5sngejunfj3lb
[+] /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/hdf5-1.8.22-j6aizwr5ksilzbtca2vl5ap6zmmvic23
==> Installing conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu
==> No binary for conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu found: installing from source
==> Using cached archive: /Users/benwibking/ascent/build/spack/var/spack/cache/_source-cache/archive/55/55c37ddc668dbc45d43b60c440192f76e688a530d64f9fe1a9c7fdad8cd525fd.tar.gz
==> No patches needed for conduit
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10'

4 errors found in build log:
     421    [  3%] Building C object thirdparty_builtin/libyaml-690a781/CMakeFiles/conduit_libyaml.dir/src/writer.c.o
     422    cd /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4w
            rjy4wkpctguu/spack-build-hdk3ps5/thirdparty_builtin/libyaml-690a781 && /usr/bin/clang  -I/private/var/folders/lz/n6jhm4hj4_l73w0m
            2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/fortran -I
            /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy
            4wkpctguu/spack-src/src/libs/conduit -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stag
            e-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/conduit/c -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340
            000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/libs/conduit -I/pri
            vate/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkp
            ctguu/spack-src/src/libs/relay -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-cond
            uit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/relay/c -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/
            benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/libs/relay -I/private/var/f
            olders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spac
            k-src/src/libs/blueprint -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.
            8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/blueprint/c -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/be
            nwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/libs/blueprint -I/private/var
            /folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/sp
            ack-src/src/thirdparty_builtin/rapidjson/include -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stag
            e/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/thirdparty_builtin/libb64-1.2.1/include -I/private/var
            /folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/sp
            ack-src/src/thirdparty_builtin/libyaml-690a781/include -O2 -g -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/
            SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -fPIC -MD -MT thirdparty_builtin/libyaml-690a781/CMakeFiles/conduit_libyaml.dir/src/wri
            ter.c.o -MF CMakeFiles/conduit_libyaml.dir/src/writer.c.o.d -o CMakeFiles/conduit_libyaml.dir/src/writer.c.o -c /private/var/fold
            ers/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-s
            rc/src/thirdparty_builtin/libyaml-690a781/src/writer.c
     423    [  3%] Linking CXX executable ../../../tests/blt_mpi_smoke
     424    cd /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4w
            rjy4wkpctguu/spack-build-hdk3ps5/blt/tests/smoke && /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang
            -13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwfc/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt --verb
            ose=1
     425    /usr/bin/clang++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=1
            2.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/
            apple-clang-13.1.6/hwloc-2.8.0-7cc4buhojst4mnf47b6z7p5muufjnynl/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monte
            rey-m1/apple-clang-13.1.6/libevent-2.1.12-5ydanoq6kz77bxdo3q5wf6n2e5xdlkry/lib -L/Users/benwibking/ascent/build/spack/opt/spack/d
            arwin-monterey-m1/apple-clang-13.1.6/pmix-4.1.2-6anltl4q3mlgadgnfjfjhlc6che4qt57/lib -Wl,-flat_namespace -Wl,-commons,use_dylibs
            -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/hwloc-2.8.0-7cc4buhojst4mnf47b6z7p5muufjny
            nl/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/libevent-2.1.12-5ydanoq6kz77bxdo3q5
            wf6n2e5xdlkry/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/pmix-4.1.2-6anltl4q3mlga
            dgnfjfjhlc6che4qt57/lib CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o -o ../../../tests/blt_mpi_smoke  /Users/benwibking/ascen
            t/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/lib/libmpi.dylib /Us
            ers/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/
            lib/libmpi_usempif08.dylib /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rp
            d4so43xty7bildeg5oxkszld33keq/lib/libmpi_usempi_ignore_tkr.dylib /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m
            1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/lib/libmpi_mpifh.dylib
     426    ld: file not found: @rpath/libquadmath.0.dylib for architecture arm64
  >> 427    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 428    make[2]: *** [tests/blt_mpi_smoke] Error 1
  >> 429    make[1]: *** [blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/all] Error 2
     430    make[1]: *** Waiting for unfinished jobs....
     431    [  3%] Built target conduit_libyaml
     432    /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwf
            c/bin/cmake -E cmake_copy_f90_mod lib/fortran/fruit.mod blt/thirdparty_builtin/fruit-3.4.1/CMakeFiles/fruit.dir/fruit.mod.stamp G
            NU
     433    /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwf
            c/bin/cmake -E cmake_copy_f90_mod lib/fortran/fruit_util.mod blt/thirdparty_builtin/fruit-3.4.1/CMakeFiles/fruit.dir/fruit_util.m
            od.stamp GNU
     434    /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwf
            c/bin/cmake -E touch blt/thirdparty_builtin/fruit-3.4.1/CMakeFiles/fruit.dir/fruit.f90.o.provides.build
     435    [  3%] Linking Fortran shared library ../../../lib/libfruit.dylib

     ...

     438    [  3%] Built target fruit
     439    [  3%] Built target conduit_civetweb
     440    [  4%] Linking CXX shared library ../../../../lib/libgtest.dylib
     441    cd /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4w
            rjy4wkpctguu/spack-build-hdk3ps5/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest && /Users/benwibking/ascent/build
            /spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwfc/bin/cmake -E cmake_link_scri
            pt CMakeFiles/gtest.dir/link.txt --verbose=1
     442    /usr/bin/clang++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=1
            2.0 -dynamiclib -Wl,-headerpad_max_install_names -o ../../../../lib/libgtest.dylib -install_name /private/var/folders/lz/n6jhm4hj
            4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/li
            b/libgtest.dylib "CMakeFiles/gtest.dir/src/gtest-all.cc.o"
     443    [  4%] Built target gtest
  >> 444    make: *** [all] Error 2

See build log for details:
  /var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-out.txt

==> Error: ascent-develop-ammwyafmmzpvs2ykqjyyqbni324mrd4s: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
[ERROR: failure of spack install/dev-build]
```

**Comment by BenWibking** [comment]
I've built it inside a linux VM and that works for now. Not sure what is going on with the macOS build.

**Comment by cyrush** [comment]
Thanks, I am tracking down the macOS issues. Will take me some time to heal the recipe and when I do I will pin spack.

**Comment by cyrush** [comment]
@BenWibking this should now be resolved in #1012, that said I don't have a monterey system to test, so something else could popup. If you try and have an issue let me know and I'll continue to help.

**Comment by BenWibking** [comment]
Ah, oops. I made a mistake and tried to get it to build with gcc instead. It looks like it's working now. Thanks again.

**Comment by BenWibking** [comment]
Ok, it made it all the way to the RAJA and Conduit builds again, but failed there with new errors:

For raja:
```
==> Installing raja-2022.03.0-plohpany5kjgudz5jcsexutthpbgfcgs
==> No binary for raja-2022.03.0-plohpany5kjgudz5jcsexutthpbgfcgs found: installing from source
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> raja: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10'

16 errors found in build log:
     118    clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
     119    clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
     120    clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
     121    clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
     122    clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
     123    In file included from /var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-raja-2022.03.0-plohpa
            ny5kjgudz5jcsexutthpbgfcgs/spack-src/src/MemUtils_SYCL.cpp:19:
  >> 124    /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-raja-2022.03.0-plohpany5kjgudz5jcse
            xutthpbgfcgs/spack-build-plohpan/include/RAJA/config.hpp:243:2: error: RAJA configured with RAJA_ENABLE_OPENMP, but OpenMP not
            supported by current compiler
     125    #error RAJA configured with RAJA_ENABLE_OPENMP, but OpenMP not supported by current compiler
```

For Conduit:
```
==> Installing conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu
==> No binary for conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu found: installing from source
==> Fetching https://github.com/LLNL/conduit/releases/download/v0.8.4/conduit-v0.8.4-src-with-blt.tar.gz
##################################################################################################################################### 100.0%
==> No patches needed for conduit
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10'

4 errors found in build log:
     421    [  3%] Building C object thirdparty_builtin/libyaml-690a781/CMakeFiles/conduit_libyaml.dir/src/writer.c.o
     422    cd /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll
            4wrjy4wkpctguu/spack-build-hdk3ps5/thirdparty_builtin/libyaml-690a781 && /usr/bin/clang  -I/private/var/folders/lz/n6jhm4hj4_l7
            3w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/fort
            ran -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzs
            mll4wrjy4wkpctguu/spack-src/src/libs/conduit -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/
            spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/conduit/c -I/private/var/folders/lz/n6jhm4hj4_l73
            w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/libs/
            conduit -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3
            izzsmll4wrjy4wkpctguu/spack-src/src/libs/relay -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stag
            e/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/relay/c -I/private/var/folders/lz/n6jhm4hj4_l73
            w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5/libs/
            relay -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3iz
            zsmll4wrjy4wkpctguu/spack-src/src/libs/blueprint -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-st
            age/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/libs/blueprint/c -I/private/var/folders/lz/n6jhm4h
            j4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-build-hdk3ps5
            /libs/blueprint -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk
            3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/thirdparty_builtin/rapidjson/include -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky
            5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/thirdparty_builtin
            /libb64-1.2.1/include -I/private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8
            .4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/thirdparty_builtin/libyaml-690a781/include -O2 -g -DNDEBUG -arch arm64 -isysr
            oot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -fPIC -MD -MT thirdparty_builtin/libyaml-690a
            781/CMakeFiles/conduit_libyaml.dir/src/writer.c.o -MF CMakeFiles/conduit_libyaml.dir/src/writer.c.o.d -o CMakeFiles/conduit_lib
            yaml.dir/src/writer.c.o -c /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-
            0.8.4-hdk3ps5bto3izzsmll4wrjy4wkpctguu/spack-src/src/thirdparty_builtin/libyaml-690a781/src/writer.c
     423    [  3%] Linking CXX executable ../../../tests/blt_mpi_smoke
     424    cd /private/var/folders/lz/n6jhm4hj4_l73w0m2yky5m340000gn/T/benwibking/spack-stage/spack-stage-conduit-0.8.4-hdk3ps5bto3izzsmll
            4wrjy4wkpctguu/spack-build-hdk3ps5/blt/tests/smoke && /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-c
            lang-13.1.6/cmake-3.23.3-bkrxuqgip4wtz7qqd2xmshjnlg2phwfc/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt
            --verbose=1
     425    /usr/bin/clang++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min
            =12.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey
            -m1/apple-clang-13.1.6/hwloc-2.8.0-7cc4buhojst4mnf47b6z7p5muufjnynl/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin
            -monterey-m1/apple-clang-13.1.6/libevent-2.1.12-5ydanoq6kz77bxdo3q5wf6n2e5xdlkry/lib -L/Users/benwibking/ascent/build/spack/opt
            /spack/darwin-monterey-m1/apple-clang-13.1.6/pmix-4.1.2-6anltl4q3mlgadgnfjfjhlc6che4qt57/lib -Wl,-flat_namespace -Wl,-commons,u
            se_dylibs -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/hwloc-2.8.0-7cc4buhojst4mnf47b
            6z7p5muufjnynl/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/libevent-2.1.12-5ydan
            oq6kz77bxdo3q5wf6n2e5xdlkry/lib -L/Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/pmix-4.1
            .2-6anltl4q3mlgadgnfjfjhlc6che4qt57/lib CMakeFiles/blt_mpi_smoke.dir/blt_mpi_smoke.cpp.o -o ../../../tests/blt_mpi_smoke  /User
            s/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/
            lib/libmpi.dylib /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xt
            y7bildeg5oxkszld33keq/lib/libmpi_usempif08.dylib /Users/benwibking/ascent/build/spack/opt/spack/darwin-monterey-m1/apple-clang-
            13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/lib/libmpi_usempi_ignore_tkr.dylib /Users/benwibking/ascent/build/spack/o
            pt/spack/darwin-monterey-m1/apple-clang-13.1.6/openmpi-4.1.4-5rpd4so43xty7bildeg5oxkszld33keq/lib/libmpi_mpifh.dylib
     426    ld: file not found: @rpath/libquadmath.0.dylib for architecture arm64
  >> 427    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 428    make[2]: *** [tests/blt_mpi_smoke] Error 1
  >> 429    make[1]: *** [blt/tests/smoke/CMakeFiles/blt_mpi_smoke.dir/all] Error 2
     430    make[1]: *** Waiting for unfinished jobs....
```

The full logs are here:
[conduit-build-out.txt](https://github.com/Alpine-DAV/ascent/files/9531176/conduit-build-out.txt)
[raja-build-out.txt](https://github.com/Alpine-DAV/ascent/files/9531177/raja-build-out.txt)

**Comment by BenWibking** [comment]
I'm able to work around the raja build issue with
`python3 scripts/uberenv/uberenv.py --install --prefix="build" --spec="^raja~openmp`.

However, the Conduit build still fails with the `libquadmath` link issue:
`ld: file not found: @rpath/libquadmath.0.dylib for architecture arm64`.

_Edit_: `libquadmath` is located at `/opt/homebrew/opt/gcc/lib/gcc/current/libquadmath.0.dylib` and is indeed built for arm64. For some reason, conduit can't find it when building. I tried adding this path to `extra-rpaths` in `scripts/uberenv_configs/spack_configs/configs/darwin/compilers.yaml`, but that didn't seem to do anything.

**Comment by cyrush** [comment]
My hunch is the issue related to `libquadmath` has to do with fortran compiler needing extra rpath to find it.

extra-rpaths should help, but maybe it needs to linked to fortran in some way?

**Comment by BenWibking** [comment]
I don't need Fortran support, so I got it to build with:
`python3 scripts/uberenv/uberenv.py --install --prefix="build" --spec="^raja~openmp^conduit~fortran`

**Comment by cyrush** [comment]
Thanks for the update, I'll keep this open to remind use to explore further when we get access to an arm mac.

**Comment by BenWibking** [comment]
We've switched to the Bash scripts to build Ascent in all cases, and those work perfectly fine on ARM Macs in our tests, so I'll close this for now.

**Comment by cyrush** [comment]
thanks for the update!
